import os
import argparse

use = '\n'\
    '        python make_nexus_for_iqtree.py -s [suffix name] -i [path to directory]'
des = 'Make nexus file from multiple fasta files generated by tools such as Orthofinder.'

psr  = argparse.ArgumentParser(
    prog = 'make_nexus_for_iqtree',
    usage = use,
    description = des,
    formatter_class=argparse.RawTextHelpFormatter
    )

psr.add_argument('-s', '--suffix', required=True, help='Suffix name of fasta files for distinguishing from unnecessary files')
psr.add_argument('-i', '--input', required=True, help='Full path to directory of fatsa files')

args = psr.parse_args()

suffix_in = args.suffix
input_dir = args.input

input_dir_all_files = os.listdir(input_dir)
files = [s for s in input_dir_all_files if suffix_in in s]

output = '#nexus\nbegin sets;\n'
cnt = 1

for f in files:
    line = '    charset part' + str(cnt) + ' = ' + f + ': ;\n'
    cnt +=1
    output += line

output += 'end;'

f = open('./partition.nexus', 'w')
f.write(output)
f.close()
